# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
