# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteshop', '0001_initial'),
        ('tickets', '0005_featurevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteshop.Order'),
        ),
        migrations.AlterField(
            model_name='featurevote',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Feature'),
        ),
    ]
