# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190623_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Bug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Feature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
